#!/usr/bin/env python3

import argparse
import os
from pathlib import Path
from typing import cast


class Args:
    dry_run: bool
    command: str
    arguments: list[str]

    @staticmethod
    def parse_args():
        parser = argparse.ArgumentParser(
            prog="ai-bwrap",
            description="Uses bubblewrap utility to give your AI agent some safe space",
        )
        _ = parser.add_argument("-d", "--dry-run",
                                help="Log the command instead of running it", action="store_true")
        _ = parser.add_argument("command",
                                help="The command (agent) to run in sandbox")
        _ = parser.add_argument("arguments",
                                help="Arguments to the command (agent)",
                                nargs=argparse.REMAINDER, metavar="...")

        return parser.parse_args()

    def __init__(self):
        args = Args.parse_args()
        self.dry_run = cast(bool, args.dry_run)
        self.command = cast(str, args.command)
        self.arguments = cast(list[str], args.arguments)


def r(path: Path) -> str:
    return path.expanduser().absolute().as_posix()


class ConstrCmd():
    __args: list[str] = []

    def ro_bind(self, path: Path):
        self.__args.extend(("--ro-bind", r(path), r(path)))

    def rw_bind(self, path: Path):
        self.__args.extend(("--bind", r(path), r(path)))

    def dev(self, path: Path):
        self.__args.extend(("--dev", r(path)))

    def proc(self, path: Path):
        self.__args.extend(("--proc", r(path)))

    def tmpfs(self, path: Path):
        self.__args.extend(("--tmpfs", r(path)))

    def share_net(self):
        self.ro_bind(Path("/run/systemd/resolve/stub-resolv.conf"))
        self.__args.append("--share-net")

    def die_with_parent(self):
        self.__args.append("--die-with-parent")

    def construct(self, cmd: str, cmd_args: list[str]) -> list[str]:
        self.__args.append(cmd)
        self.__args.extend(cmd_args)
        return self.__args


def prepare_command(cmd: str, args: list[str]) -> list[str]:
    bwrap = ConstrCmd()
    bwrap.ro_bind(Path("/"))
    bwrap.rw_bind(Path(os.getcwd()))
    bwrap.dev(Path("/dev"))
    bwrap.proc(Path("/proc"))
    bwrap.tmpfs(Path("/run"))
    bwrap.tmpfs(Path("/tmp"))
    bwrap.share_net()
    bwrap.die_with_parent()

    if (cmd == "pi"):
        config_dir = Path(os.environ.get("PI_CODING_AGENT_DIR", "~/.pi"))
        bwrap.rw_bind(config_dir)
    elif (cmd == "opencode"):
        config_home = Path(os.environ.get("XDG_CONFIG_HOME", "~/.config"))
        config_dir = Path(os.environ.get("OPENCODE_CONFIG_DIR",
                                         config_home.joinpath("opencode")))
        data_dir = Path(os.environ.get("XDG_DATA_HOME",
                                       "~/.local/share")).joinpath("opencode")
        state_dir = Path(os.environ.get("XDG_STATE_HOME",
                                        "~/.local/state")).joinpath("opencode")
        cache_dir = Path(os.environ.get("XDG_CACHE_HOME",
                                        "~/.cache")).joinpath("opencode")
        bwrap.rw_bind(config_dir)
        bwrap.rw_bind(data_dir)
        bwrap.rw_bind(state_dir)
        bwrap.rw_bind(cache_dir)
    elif (cmd == "codex"):
        config_dir = Path(os.environ.get("CODEX_HOME", '~/.codex'))
        bwrap.rw_bind(config_dir)

    return bwrap.construct(cmd, args)


def log_command(cmd: list[str]):
    print("bwrap", *cmd)


def run_command(cmd: list[str]):
    os.execvp("bwrap", ["bwrap", *cmd])


def main():
    args = Args()
    cmd = prepare_command(args.command, args.arguments)
    if args.dry_run:
        log_command(cmd)
    else:
        run_command(cmd)


if __name__ == "__main__":
    main()
